[package]
name = "kernel-micro"
version = "0.0.0"
edition = "2021"

[dependencies]
app = { path = "../app" }
kernel = { path = "../kernel" }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["fs", "signal"] }

[lints]
workspace = true
