[package]
name = "publish"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { "path" = "../common" }
publish-ghost = { "path" = "../publish-ghost" }
publish-stencila = { "path" = "../publish-stencila" }

[lints]
workspace = true
