[package]
name = "node-patch-derive"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
common = { path = "../common" }
darling = "0.20.10"
format = { path = "../format" }

[lints]
workspace = true
