[package]
name = "publish-ghost"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { "path" = "../codec" }
codec-text = { "path" = "../codec-text" }
common = { "path" = "../common" }
document = { path = "../document" }
jsonwebtoken = {version = "9", default-features = false }
schema = { "path" = "../schema" }
secrets = { "path" = "../secrets" }
url = "2.5"

[lints]
workspace = true

