[package]
name = "secrets"
version = "0.0.0"
edition = "2021"

[dependencies]
cli-utils = { path = "../cli-utils" }
common = { path = "../common" }
keyring = { version = "3.6.1", features = ["apple-native", "windows-native", "sync-secret-service"]}

[lints]
workspace = true
