[package]
name = "codec-pandoc"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-text-trait = { path = "../codec-text-trait" }
pandoc_types = "0.6.0"
which = "7.0.1"

[lints]
workspace = true
