[package]
name = "codec-text-trait"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-info = { path = "../codec-info" }
codec-text-derive = { path = "../codec-text-derive" }

[lints]
workspace = true
