[package]
name = "models-stencila"
version = "0.0.0"
edition = "2021"

[dependencies]
cached = { workspace = true }
cloud = { path = "../cloud" }
model = { path = "../model" }

[lints]
workspace = true
