# Workflow for testing Rust core on multiple platforms
#
# Extends the main `test.yml` workflow by running `make -C rust lint test`
# on several platforms (whereas `test.yml` build all modules, including
# `web` and `vscode` on Ubuntu only).
#
# Intended to be run manually for specific branches, commits, or tags
# rather than on every push.

name: Test Rust
on:
  workflow_dispatch:
    inputs:
      platforms:
        description: "Platforms to test on (comma-separated: ubuntu,mac,windows)"
        type: string
        default: "ubuntu,mac,windows"

env:
  RUST_VERSION: "1.81.0"

jobs:
  test-rust:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - mac
          - windows
    runs-on: ${{ matrix.platform }}-latest
    if: contains(inputs.platforms, matrix.platform)
    
    steps:
      - uses: actions/checkout@v4
          
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy
          
      - uses: Swatinem/rust-cache@v2
      
      - name: Install Python dependencies
        run: pip install ruff pyright
        
      - name: Run tests
        run: make -C rust lint test
